### ISSUE TITLE
Add buy NFT to the onboarding Next steps

### ISSUE THREAD

**Issue by landitus** [blockstack/blockstack-app#2249]
As we are wrapping up the onboarding's [Next steps](https://github.com/hirosystems/stacks-wallet-web/pull/2233), we've realized that buying an NFT could be a more attractive next step in the onboarding. Let's explore this change by linking to https://stxnft.com/ perhaps. 

cc/ @eugeniadigon we'll need your help on an illustration!

**Comment by ginny-d** [comment]
Just for context, which step are we replacing with this one?

**Comment by andresgalante** [comment]
@eugeniadigon We haven't decided yet, but buying a btc name turned out to be a bad first experience for Fernando and Sully. That's why we are exploring what would be the first first experience we can suggest our users to be their first transaction.

**Comment by ginny-d** [comment]
Got it, I'll try my best to have it by end of this week (at latest start of next week)

**Comment by andresgalante** [comment]
This is not urgent though. @markmhx what do you think?

**Comment by landitus** [comment]
Not urgent at all. We'll release the Next steps as-is. Then, I can start working with a placeholder illustration and share it here first.

**Comment by ginny-d** [comment]
Had some time today to work on this, what do you think?

<img width="1352" alt="a" src="https://user-images.githubusercontent.com/78865845/155361942-f40bacb6-2368-4263-9dbc-b216770039cb.png">

<img width="488" alt="Home" src="https://user-images.githubusercontent.com/78865845/155361958-47b643aa-640c-4ca2-ba09-aea953418f8f.png">


Figma: https://www.figma.com/file/GShZH28L05eyKjRZxPb8SK/%E2%9C%8F%EF%B8%8FIllustration-System?node-id=102%3A4755

**Comment by landitus** [comment]
Looks good to me! 🍌

**Comment by andresgalante** [comment]
🍌 = perfect

Btw, what's the deal with NFTs and some monkeys/apes/gorilas?

**Comment by ginny-d** [comment]
For me the 🍌  serves a double meaning: 1) for the most famous NFT collection in Stacks, without being too obvious and 2) for referencing [this very famous](https://extraordinairebanane.fr/wp-content/uploads/2018/05/andy-wahrol-banane.png) piece of art

**Comment by fbwoolf** [comment]
@markmhx @andresgalante should I take this on now and get it swapped out before we release it? Would be easy to change.

**Comment by landitus** [comment]
I'm waiting for feedback from @markmhx on the copy. 

Once I have it, shall I move it to the "Development" column so it's available for picking it up?

**Comment by fbwoolf** [comment]
> 
> 
> Once I have it, shall I move it to the "Development" column so it's available for picking it up?

Typically the dev will move it into `Development` once they start it, so just let me know here when the copy is ready.

**Comment by fbwoolf** [comment]
Maybe having you move it into `Development` is a better process? Not sure but open to it.

**Comment by andresgalante** [comment]
> should I take this on now and get it swapped out before we release it? Would be easy to change.

I'd say yes. We won't have a release for the next 2 weeks, and we will still need to release 2172 before anything else.

> Maybe having you move it into Development is a better process? Not sure but open to it.

I want the board to be a reflection of the state of the work. So, until you start working on it, let's not move it to in development.

**Comment by markmhendrickson** [comment]
For the copy:

- **Header**: "Buy an NFT" _(note the "an" not "a")_
- **Subheader**: "Collect and trade NFTs secured by Bitcoin" 
- **Link**: "Find NFT"

**Comment by landitus** [comment]
Thanks @markmhx! @fbwoolf here's the final design.

<img width="1352" alt="Buy an NFT (lg)" src="https://user-images.githubusercontent.com/239215/155983655-63d70f65-0601-44b0-8e06-abe83a4087c2.png">
<img width="488" alt="Buy an NFT (sm)" src="https://user-images.githubusercontent.com/239215/155983657-a72d175d-365d-4ad3-b8f5-a07e50a7866d.png">

[Figma](https://www.figma.com/file/1hT5X43DR8KCuFFZEFlMV4/%F0%9F%9B%AB-Onboarding?node-id=805%3A6526)

**Comment by Eshwari007** [comment]
@fbwoolf @landitus 
Based on @markmhx input above:
Header: "Buy an NFT" (note the "an" not "a")
Subheader: "Collect and trade NFTs secured by Bitcoin"
**Link: "Find NFT"** this seems incorrect on the UI

But in actual UI:

<img width="261" alt="Screen Shot 2022-03-23 at 2 22 31 PM" src="https://user-images.githubusercontent.com/38872890/159769474-24548d01-71dc-4b98-a65c-9b76fd53542c.png">

**Comment by landitus** [comment]
> Link: "Find NFT" this seems incorrect on the UI

Indeed, it's incorrect. @fbwoolf can you change the copy?

**Comment by fbwoolf** [comment]
> > Link: "Find NFT" this seems incorrect on the UI
> 
> Indeed, it's incorrect. @fbwoolf can you change the copy?

Yep, no prob, I'll just change it on the Moonpay branch bc I've already merged this work into dev. I thought QA was done.

**Comment by Eshwari007** [comment]
> > > Link: "Find NFT" this seems incorrect on the UI
> > 
> > 
> > Indeed, it's incorrect. @fbwoolf can you change the copy?
> 
> Yep, no prob, I'll just change it on the Moonpay branch bc I've already merged this work into dev. I thought QA was done.

No @fbwoolf .Maybe I should have mentioned it clearly earlier, sorry abt that. I still have a few more validation on the next steps onboarding testing. Mostly minor ones but should wrap them up by eod.

**Comment by fbwoolf** [comment]
> 
> No @fbwoolf .Maybe I should have mentioned it clearly earlier, sorry abt that. I still have a few more validation on the next steps onboarding testing. Mostly minor ones but should wrap them up by eod.

Sorry I misunderstood. I made a new commit on the Moonpay branch `fix: onboarding ui` so I'll add any more needed changes there as well.
