### ISSUE TITLE
Resolve forever pending state on home screen

### ISSUE THREAD

**Issue by markmhendrickson** [blockstack/blockstack-app#2718]
This has been reported a couple of times in the past 24 hours, from one user who says they had to sign out and back in to resolve it, and from another who doesn't want to sign out because they haven't saved their Secret Key yet.

I asked one of the users to provide developer console and network information, but nothing unusual seems to appear.

One has 60 accounts and I assume the other has many as well, in case relevant.

![image](https://user-images.githubusercontent.com/28991/195601472-1a57c6ac-a69a-44e8-a33c-36c5e05b7545.png)
![image](https://user-images.githubusercontent.com/28991/195601802-9382e2c5-5386-41e7-bd43-ff74cccab2c4.png)
![image](https://user-images.githubusercontent.com/28991/195601842-b5a22313-1e39-466a-9409-c6e6a81ea428.png)

**Comment by kyranjamie** [comment]
This'll be tricky to debug unless we get more info than this or can repro ourselves

**Comment by kxshagra** [comment]
Hey,
I've been facing that issue , can you let me know which information do you need

**Comment by kyranjamie** [comment]
We've pushed a new release, `v3.18.2` which may fix the issue. When this is in the Chrome store, probably in a couple of hours, would you be able to test again @kxshagra ?

**Comment by kxshagra** [comment]
ohh ty for pushing update soo quick , I'll let you know if it's fixed or not when new release is be up

**Comment by kxshagra** [comment]
I tried the new update but still it isn't fixed , I'm still getting that loading screen

**Comment by markmhendrickson** [comment]
@kxshagra We're looking into adding some diagnostic capabilities that will help us debug this issue for you further: https://github.com/hirosystems/stacks-wallet-web/issues/2727

**Comment by markmhendrickson** [comment]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/28991/197381536-5d1f3202-80bb-4b64-b35b-5516920b9acd.png">

**Comment by markmhendrickson** [comment]
We have new diagnostic capabilities in v3.22.0, which was just released. @kyranjamie want to jump on a call with @kxshagra to see if they help diagnose this problem?

**Comment by kxshagra** [comment]
yeah sure , I'm ready to jump on a call
