### ISSUE TITLE
Resolve issues while signing messages with certain formats

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/blockstack-app#2725]
Some messages are being immediately rejected by the Ledger. This was highlighted by [Gamma.io](gamma.io)'s msg signing auth.

Our test app uses a pretty long string of

https://github.com/hirosystems/stacks-wallet-web/blob/b5a36f10e478037654ed9c93011a1d826f7329a7/test-app/src/components/signature.tsx#L44-L45

which signs without problem.

Gamma's message, that looks like...

```
Welcome!
Sign this message to access Gamma's full feature set.
As always, by using Gamma, you agree to our terms of use: https://gamma.io/terms
Domain: gamma.io
Account: SP2PH3XAPDMSKXQVS1WZ80JGZACY713JQQEE1DY48
Nonce: c83024f9e9aef40f5d72076e883054c07100035112826b14f78e5a893d62b1bf
```

...fails. It's not immediately clear why. Our test example is longer, so it doesn't appear length related. Removing carriage returns & punctuation also doesn't completely fix the issue.

**Comment by 314159265359879** [comment]
A user is reporting that signing a message on console to login failed with this error: "Your ledger device has rejected the payload stating it is invalid"

![image](https://user-images.githubusercontent.com/33360391/200778494-aac93903-8038-46fb-b222-141a344665a4.png)

**Comment by 314159265359879** [comment]
A user encountering similar problems, it is likely related to this issue.

**Comment by markmhendrickson** [comment]
@kyranjamie this should be resolved fully by https://github.com/Zondax/ledger-stacks/pull/138, correct?

**Comment by kyranjamie** [comment]
Yes, it should. though it'd be great if we could test the actual app throwing this error. Edge cases have been missed in the past because of an untested apps. I've made an _App Support_ db in Notion to track support/internal QA of apps.

**Comment by TJustin602** [comment]
hi. still getting this error when trying to authenticate on gamma.io . more than happy to show the message :)

**Comment by 314159265359879** [comment]
> hi. still getting this error when trying to authenticate on gamma.io . more than happy to show the message :) 

Thanks @TJustin602 unfortunately Ledger has not yet approved our fix for this issue. This is expected to be fixed when Stacks app for Ledger live is at version 0.23.4 or higher.

**Comment by TJustin602** [comment]
Thanks very much for the update !

**Comment by kahnanX** [comment]
got the same error message, just to log my case , I know I need to wait until ledger to work on this issue...

**Comment by friedger** [comment]
Stack address field in a Blocksurvey causes the same issue for users.

**Comment by markmhendrickson** [comment]
This continues to await security review on Ledger's end 😢

**Comment by kyranjamie** [comment]
I've tested the Gamma.io flow that was previously broken. With Stacks app `v0.24.2` I'm able to sign the message successfully.
