### ISSUE TITLE
5th+ Account inaccessible in Extension Mode

### ISSUE THREAD

**Issue by dt665m** [blockstack/blockstack-app#4549]
This might be related to #3488.  Currently if I create more than 5 accounts, the 6th one will be blocked by the "Create New Account" button and the only way to access them is to go into full screen mode in another tab.

Screenshot:
![Screenshot 2023-11-21 at 12 54 51 PM](https://github.com/leather-wallet/extension/assets/11184257/99b3c852-47cb-4070-9e71-5a16fffd6c54)

**Comment by pete-watters** [comment]
Thanks for reporting this @dt665m. This is a known issue I will be fixing soon. 

I'll close this issue and let you know when it's resolved in https://github.com/leather-wallet/extension/issues/4371 so you can check

**Comment by 314159265359879** [comment]
@pete-watters This looks like it is not resolved (anymore). would you mind taking a look?

**Comment by pete-watters** [comment]
> #4371

It's not fixed yet but I closed this as a duplicate [as per ](https://github.com/leather-wallet/extension/issues/4549#issuecomment-1820538681)
